### ISSUE TITLE
Precompiled version

### ISSUE THREAD

**Issue by TheGiolly** [bjaraujo/Bombermaaan#15]
Hi, sorry if I'm opening an issue for this, but is there a precompiled version of this?
If so, where can I find it?
Thanks in advance
Keep up the great work

**Comment by Fixer-007** [comment]
https://github.com/bjaraujo/Bombermaaan/releases ?

**Comment by bjaraujo** [comment]
Hi, 

There are 4 precompiled versions in the release section: 

 - Bombermaaan_1.8.6.1674.zip: portable version (no installation necessary),
 - Bombermaaan_1.8.6.1674_setup.exe (Windows setup, tested on windows 10)
 - Bombermaaan_1.8.6.1674_i386.deb (Linux version, tested on Ubuntu)
 - Bombermaaan_1.8.6.1674_arm.deb (Arm version, tested on Raspbian)

Hope this helps.

**Comment by yukulele** [comment]
There are no precompiled debian versions (deb files) for versions above 1.8.6

is it possible to provide them for the latest version?
