### ISSUE TITLE
remember team settings 

### ISSUE THREAD

**Issue by msjasinski** [bjaraujo/Bombermaaan#18]
Remember team settings from previous game - now you have to choose every time you start playing your player and computer players. Other settings are kept.

**Comment by bjaraujo** [comment]
Hi,

Makes sense.
Will add that feature to next release.

**Comment by bjaraujo** [comment]
Hi, 

The latest version saves the team settings in config.xml:

<BomberTeams bomber0="1" bomber1="0" bomber2="0" bomber3="1" bomber4="1" />
