### ISSUE TITLE
eliminate waiting time

### ISSUE THREAD

**Issue by msjasinski** [bjaraujo/Bombermaaan#19]
I appreciate shortening waiting time in winning(game&tournament)/drawing, but I would suggest eliminate it altogether (on clicking space/return), because it slows the game down and serves no purpose.

**Comment by bjaraujo** [comment]
I have reduced the minimum timing to 0 so once you click "return" it will just go away.

**Comment by msjasinski** [comment]
Thanks! I will test when the new binaries are ready.

**Comment by msjasinski** [comment]
It plays great, thanks!
Minimum timing 0 is still missing when the match ends in a draw.

**Comment by msjasinski** [comment]
I would also set minimum timing when one of the players/teams (or both players/ teams) gets killed. Now you have to wait a few seconds for some unimportant/secondary actions to finish.

**Comment by bjaraujo** [comment]
Will check the draw time. 

"I would also set minimum timing when one of the players/teams (or both players/ teams) gets killed"
You mean when both human players have lost and you have to wait for CPU playes to finish?

**Comment by msjasinski** [comment]
> You mean when both human players have lost and you have to wait for CPU players to finish?

Yes. When human/AI single/team player(s) have won/lost, there are still a few actions you have to watch. Sometimes it is interesting to see, but sometimes you just want to get on to the next game. As I said, it is not vital. Drawing matches are more important.

**Comment by bjaraujo** [comment]
Fixed with commit:
197096a5c11ecb5ddaaefa98e694cf4c23bf1262
