### ISSUE TITLE
Ability to change window size

### ISSUE THREAD

**Issue by Fixer-007** [bjaraujo/Bombermaaan#20]
Currently game runs under 640x480 windowed (quite tiny) or fullscreen (with somewhat fuzzy picture).

Few ideas:
+ Make game in windowed mode resizable as any window (keeping correct aspect ratio), so you can maximise it to any size you like (even 4K), with some good upscaling making picture sharp.
+ Make fullscreen mode actually use current monitor resolution with some good upscaling (not sure).

**Comment by bjaraujo** [comment]
Yes, that is a good suggestion. There are some problems with full screen mode in SDL. There is a DIRECTX version as well that can be explored. Need to check which mode would be better to do this. The SDL version has one big advantage is that it is cross-platform. But I can maybe release also DIRECTX versions of the game for windows users.
