### ISSUE TITLE
Exit match UI

### ISSUE THREAD

**Issue by Fixer-007** [bjaraujo/Bombermaaan#21]
![default](https://user-images.githubusercontent.com/16494741/33693680-cd2cfc02-dafc-11e7-8c2b-42e9cf328c74.png)

Active selected should probably be in green, not in white (IMO).

**Comment by bjaraujo** [comment]
Yes, that can be a bit confusing. The original text color was green and then highlights are white. I guess it could have a redesign.

**Comment by bjaraujo** [comment]
Fixed with commit: c638e24e816d2aba46988750ae440fd35dad97b3
