### ISSUE TITLE
Ability to play with more Joysticks

### ISSUE THREAD

**Issue by phreakazoid** [bjaraujo/Bombermaaan#24]
Is it possible to play with more Gamepad/Joysticks?

**Comment by bjaraujo** [comment]
Yes, I have tested at home with these:

https://www.amazon.co.uk/Promotions%E3%80%91EasySMX-Wireless-Controller-Portable-Joystick-Gamepad-Black-Blue/dp/B01KV7B2CG/ref=sr_1_1?s=amazon-devices&ie=UTF8&qid=1519754460&sr=8-1&keywords=wireless+game+controller+pc

https://www.amazon.co.uk/gp/product/B01N5966NJ/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1

https://www.amazon.co.uk/SNES-Controller-Pad/dp/B004MTHP94/ref=sr_1_4?s=videogames&ie=UTF8&qid=1519754566&sr=1-4&keywords=snes+controller
