### ISSUE TITLE
The game doesn't run

### ISSUE THREAD

**Issue by atolstoy** [bjaraujo/Bombermaaan#25]
I can't get this game to run under Linux. Please provide some straightforward instructions about what steps one need s to complete in order to run Bombermaaan.
So far I compiled the Bombermaan executable by running
cmake . -DLOAD_RESOURCES_FROM_FILES:BOOL=ON
in the trunk directory. The executable is located in trunk/src, but I see there is no target for 'make install' in your Makefile, so I've just left with that executable alone. When I place it one level up (in order to make it detect levels) it still doesn't do anything, just hangs for a little while and then exits.
I'd be glad to finally run this game in Linux of you provide more details about how to do it. Thanks in advance.

**Comment by bjaraujo** [comment]
Hi,

If you look at this script you can see what is necessary to run:

https://github.com/bjaraujo/Bombermaaan/blob/master/retropie/bombermaaan.sh

Besides compiling it, you need to copy levels, images and sounds directory to the same directory of the executable. If you enable logging you can also see what error it is giving.

**Comment by atolstoy** [comment]
Does it make sense if I just copy the Bombermaaan executable one level up (to trunk) and not the other way around? The game doesn't work, it just changes my screen resolution to 640x480 and exits with no log messages.
Please try it yourself and share results.

**Comment by bjaraujo** [comment]
No, because that way it still can't find images and sounds directories which are in res.

It has to be:

bombermaaan
- images
- sounds
- levels

**Comment by atolstoy** [comment]
Ok, I figured it out. Thanks!
