### ISSUE TITLE
[Advice] Change default game setting for better user experience

### ISSUE THREAD

**Issue by cswef** [bjaraujo/Bombermaaan#26]
Thank you for this excellent game project.

Advice:
I hadn't realize this open source game project has AI for a long time, until one day I accidentally pressed the arrow key in the game setting screen. I suggest changing the default game setting (as the following screen shot.The second player is set as COM),so that new user could quickly realize the game has AI system.

![advice](https://user-images.githubusercontent.com/17522466/44618481-3233e000-a8a9-11e8-9175-78d6621410b4.png)

**Comment by bjaraujo** [comment]
Hi, 

Sounds reasonable will do that change for next release.

**Comment by bjaraujo** [comment]
@cswef Hi, what is the platform you using?
Is that windows, Linux, etc.?

**Comment by cswef** [comment]
platform: win8 x64

release version:
https://github.com/bjaraujo/Bombermaaan/releases/tag/v1.9.3.1905

**Comment by bjaraujo** [comment]
The latest version has COM-Computer as second player by default.
