### ISSUE TITLE
detonator ??

### ISSUE THREAD

**Issue by pamonnier** [bjaraujo/Bombermaaan#27]
Merci pour cette évolution de Bomberman. Avec mes collègues nous jouons sur la pause de midi. c'est vraiment très intéressant de jouer à 4 et très dôle.

Où en es-tu sur le menu pour activer et modifier certaines options du jeu?

Et pourquoi il n'y a plus de détonateur dans le jeu ? (ils sont dans la version 1.4)

Merci et bonne continuation

Thank you for this evolution of Bomberman. With my colleagues we play on the lunch break. it's really very interesting to play 4 and very dole.

Where are you on the menu to activate and modify options of the game?

And why is there no detonator in the game? (in 1.4 version)

![detonator](https://user-images.githubusercontent.com/44919120/48299279-3eeccb00-e4cb-11e8-8235-42e31d1d8fbb.JPG)

Thank you and good luck

**Comment by bjaraujo** [comment]
Hi,

There is still a detonator. Have a look at level 12.

![image](https://user-images.githubusercontent.com/5067963/48369329-22f54f00-e6ae-11e8-98f2-92b5c38b1f37.png)
