### ISSUE TITLE
Feature suggestion: Sprite Change Option

### ISSUE THREAD

**Issue by Sangabc** [bjaraujo/Bombermaaan#28]
I think we should have a sprite changing menu. Like chage the grass texture to snow desert and ect to make the game more alive and variety. Maybe custom sprite for level by making a separate folder to store custom sprite. Maybe even a character selection screen too. It maybe too much to ask but i really hope itll be a bew feature in future build

**Comment by bjaraujo** [comment]
Yes, that is a good suggestion. I have been wanting to do a theme selection option.
