### ISSUE TITLE
[Small Advice] Option for choosing background music

### ISSUE THREAD

**Issue by gceboh** [bjaraujo/Bombermaaan#30]
In my personal opinion,the old background music sounds better (used in the previous version:1.9.4.2045).
Different people may prefer different style of music.
Therefore,I suggest add an option for user to choose background music.

**Comment by gceboh** [comment]
And another simple solution is to store audio in independent `*.ogg`  files, rather than store it in `bombermaaan32.dll`.

Directory structure then looks like this:
```
\Bombermaaan_1.9.5.2072
│	Bombermaaan.exe
│	Bombermaaan.pdb
│	bombermaaan32.dll
│	vcruntime140.dll
├─Levels
│		L01.TXT	1.17 KB
│		L02.TXT	1.17 KB
└─Sounds
		1.ogg 
		2.ogg
```


 In this way, user could **replace music easily without recompiling the whole project**.

**Comment by bjaraujo** [comment]
That is the way it is done in Linux. On windows, it is usually loaded from DLL resource. It would be possible to build a windows version that loads resources from file using cmake flag: 

cmake . -DLOAD_RESOURCES_FROM_FILES:BOOL=ON

**Comment by gceboh** [comment]
Thanks for the detailed reply !
