### ISSUE TITLE
I am a newbie, I have a problem in make, I hope you can help me.

### ISSUE THREAD

**Issue by yuanfu141** [bjaraujo/Bombermaaan#33]
![image](https://user-images.githubusercontent.com/24367761/67090823-ad5b0280-f1dd-11e9-9f47-04e450c4aaa9.png)

**Comment by yuanfu141** [comment]
bao@bao:~/Bombermaaan/trunk$ make
[  7%] Built target tinyxml
[100%] Built target Bombermaaan

**Comment by bjaraujo** [comment]
What is the problem?
Seems you built without errors.
If you are wondering why it doesn't run then that is because you need the directory structure: levels, images, sounds, etc.

**Comment by yuanfu141** [comment]
Thanks for the quick reply，forgive me for not being good at English.
How to run,This is really my problem.
Shouldn't there be an executable file?I did not find the executable file，Is to create the directory structure under the trunk folder

**Comment by bjaraujo** [comment]
The executable is just Bombermaaan if you built on Windows it would be Bombermaaan.exe.

About the structure you look at the Linux build script.

**Comment by yuanfu141** [comment]
![image](https://user-images.githubusercontent.com/24367761/67093140-8b647e80-f1e3-11e9-8248-8bcfac21d268.png)
I still haven't found Bombermaaan.

**Comment by bjaraujo** [comment]
Search under src or src/Bombermaaan

**Comment by yuanfu141** [comment]
Thank you so much, this project is really great.

**Comment by bjaraujo** [comment]
Output now is made to ${CMAKE_BINARY_DIR}/bin.
