### ISSUE TITLE
Not playable if installed in system

### ISSUE THREAD

**Issue by algent-al** [bjaraujo/Bombermaaan#34]
Hi! First thank for continuing this project. 

I tried to package this game on Solus Budgie 4.1, installed it and  then tried to launch it.
After launching it only change my screen resolution to 640x480  and then nothing I just have to logout and then login.

If i copy the builded game in any folder in home dir, the app is launching fine.
Played a few games.

So can you help to make it payable if I install it on system?

This is the [file list](https://hasteb.in/jujoxoba.shell)  
and this is [package.yml](https://hasteb.in/hamayeno.sql)

**Comment by algent-al** [comment]
It is working also if I cd to installed directory:
`cd /usr/share/Bombermaaan/`
and then run `./bombermaaan`

**Comment by bjaraujo** [comment]
Hi,

That is odd. At this point I am not sure what the problem is, would have to test and/or debug. My initial guess would be some wrong settings file. I will try and check better tomorrow. You can also try enabling debug and logging.

**Comment by algent-al** [comment]
OK builded with `cmake -DENABLE_LOG:BOOL=ON -DENABLE_DEBUG_LOG:BOOL=ON`
Run the game and I found these two files in `$HOME/.Bombermaaan
[debug.log](https://hasteb.in/itejuwic.coffeescript) and [log.txt](https://hasteb.in/fecucapa.makefile)

Also found a way to make this game run on system, just by adding a script with name `bombermaaan` in `/usr/bin/`
```
#!/bin/bash

pushd /usr/share/Bombermaaan && ./bombermaaan && popd
```

**Comment by bjaraujo** [comment]
This code was done by several authors and I think the loading of sprites is not as robust as the loading of levels. From the log seems it is loading sprites using relative paths which isn't good. I might try and fix this.

**Comment by bjaraujo** [comment]
I have changed this. I hope it works better with absolute paths.

**Comment by algent-al** [comment]
Thank you very much. It is working fine.
![bombermaaan](https://user-images.githubusercontent.com/46356616/73593193-70ebb200-4501-11ea-808a-529c04f54748.png)

Thanks also for tagging a new release.
