### ISSUE TITLE
New version installs, doesn't load, reports lack of msvcp140d.dll

### ISSUE THREAD

**Issue by msjasinski** [bjaraujo/Bombermaaan#35]
v1.9.7.2126 is affected,  v1.9.6.2074 is not.
Windows 7 64bit.

**Comment by bjaraujo** [comment]
Can you try the latest one? 
v2.0.0.2142

**Comment by msjasinski** [comment]
Doesn't run, different file missing (ucrtbased.dll)
![bombermaaan](https://user-images.githubusercontent.com/4431194/77356448-9bf6c300-6d46-11ea-9326-f7ede8af9524.png)

**Comment by bjaraujo** [comment]
Ok. Can you try v2.0.2? 
The problem was the output directory was wrong so it was adding the debug version.

**Comment by msjasinski** [comment]
It works.
Thanks for your great work!
