### ISSUE TITLE
[Feature request] Add displays options  

### ISSUE THREAD

**Issue by sourcecode-reloaded** [bjaraujo/Bombermaaan#39]
> F3...... : set 640x480 display mode
> F4...... : set windowed display mode

Can you add these settings to options? Not just keyboard press. (This is the first i go to change to window mode).

Thank you for your great work.

**Comment by bjaraujo** [comment]
There is already a setting for this:

        <DisplayMode value="3" />

in config.xml. This file is created first time you run the game. It is stored locally or in C:\Users\<USERNAME>\AppData\Roaming\Bombermaaan.

value="3" => F3
value="4" => F4
