### ISSUE TITLE
add more levelsets

### ISSUE THREAD

**Issue by msjasinski** [bjaraujo/Bombermaaan#42]
I know a player can add extra levelsets but why not include them in the game main download?

https://www.moddb.com/games/bombermaaan/addons/level-pack-151-levels
https://web.archive.org/web/20110117132745/http://www.stud.uni-karlsruhe.de/~uabdq/bombermaaan/levels.php

**Comment by bjaraujo** [comment]
There are in trunk/levels/extended.

The I don't add them in the official release because they haven't been tested. Also if anyone wants them, they can copy them to levels folder.

There is also a level designer program developed in C#.

**Comment by msjasinski** [comment]
I see.

I can test them (if I'm given testing guidelines).

The reason for inclusion is that otherwise they have to be added manually with every new release. It's tedious.

**Comment by bjaraujo** [comment]
Hi, testing is just making sure they load properly and are not duplications of other levels. I don't bto add too many levels which look the same.

**Comment by msjasinski** [comment]
Thanks! Sorry I didn't help... I would like to test but there are no binaries.

**Comment by bjaraujo** [comment]
There are windows binaries here: https://github.com/bjaraujo/Bombermaaan/releases/tag/v2.1.8.2208
