### ISSUE TITLE
Add an icon and a desktop file.

### ISSUE THREAD

**Issue by algent-al** [bjaraujo/Bombermaaan#44]
Hi. Can you add an icon file like `Bombermaaan.svg` or `Bombermaaan.png` and the `bombermaaan.desktop` file, both required for linux installations.

**Comment by bjaraujo** [comment]
Hi, sure I will have a look into that.

**Comment by bjaraujo** [comment]
Btw, if you would like to add that in a pull request, I would be happy to review that and accept it.

**Comment by algent-al** [comment]
Closing per  28bf45a
