### ISSUE TITLE
Flathub

### ISSUE THREAD

**Issue by Mailaender** [bjaraujo/Bombermaaan#48]
I added this to https://github.com/flathub/flathub/pull/3168 even though it seems you regressed in terms of https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard compared to the original on SourceForge.

**Comment by magic-ian** [comment]
The Flatpak app does not seem to work, reviews since 2022 say it does not open. It is in much need of love.

**Comment by Mailaender** [comment]
There are no reports at https://github.com/flathub/com.github.bjaraujo.Bombermaaan/issues

**Comment by magic-ian** [comment]
> There are no reports at https://github.com/flathub/com.github.bjaraujo.Bombermaaan/issues

Some people leave reviews without filing bugs. I am filing a bug, without leaving a review. Additionally, the flatpak on flathub links to this repository, not the flathub repository. 

32 of the 44 reviews are 1-star. Attached are two of those reviews mentioning it doesn't open unfortunately.
![image](https://github.com/user-attachments/assets/1939f758-0a21-4136-9ec3-18f27f6c20a6)

**Comment by Mailaender** [comment]
Those are not displayed on the @flathub website nor on @kde Discover.
