### ISSUE TITLE
Joystick doesn't work on linux

### ISSUE THREAD

**Issue by yukulele** [bjaraujo/Bombermaaan#52]
Hi,
I'm on Kubuntu 20.04
I have plugged joystick before running the game,
The joystick is detected by others games,
I'm unable to select joystick on Bombermaaan, only keyboard 1 to 5 are suggested.

How to make joystick work on Linux?

**Comment by yukulele** [comment]
finally this bug (and others)  only come with the flatpak version.

@Mailaender it's a know bug?

**Comment by Mailaender** [comment]
https://github.com/flatpak/xdg-desktop-portal/issues/536
